### PR TITLE
Adopt the use of shadow dom for `react-modals`

### PR DESCRIPTION
**Pull request by sjd78**
There are a few advantages for using a shadow root / shadow dom technique when handling our modals rendering in webadmin:

  - CSS of the modal is fully contained in the shadow root

  - webadmin's styles will not be affected by the plugin styles

  - plugin styles will (mostly) not be affected by webadmin's styles

  - plugins can use different versions of things from the hosting webadmin document

  - There are no flashes of unstyled/misstyled content in Chrome!

Change details:
  - Upgrade react, react-dom and testing deps to ~17.0.0

  - Change CSS from just `:root` to `:root, :host` to have the global CSS variables apply to the shadowRoot

  - New custom hook `useWebAdminContext` manages modal target DOM elements properly for both plugin `renderComponent()` modals and for modals on dashboard

**Note**: The only visual difference will be no FOUC when modals open.  It works well on Firefox, Chome, and Chromium

### CODE REVIEW

**Comment by sjd78** [comment]
Requires nodejs-modules pre-seed: https://github.com/oVirt/ovirt-engine-nodejs-modules/pull/31

**Review by rszwajko — COMMENTED** [review]
All the modals are wrapped in `renderComponent` which provides access to shadow root under some ID (i.e. `host-copy-networks-modal`) but then the `PluginApiModal` seems to create another shadow root under different ID (i.e. `host-copy-network-modal`). Sometimes the IDs used are very different, sometimes they seem a typo (like the example with `HostCopyNetworksModal` and there are cases where the ID is the same i.e.  `VmExportModal`. 
Do we need 2 shadow roots here?  If not then perhaps the `PluginApiModel` can wait until `modalContext.renderContainer` will show up.

**Comment by sjd78** [comment]
> All the modals are wrapped in `renderComponent` which provides access to shadow root under some ID (i.e. `host-copy-networks-modal`)

all of them except the modals from dashboard

> but then the `PluginApiModal` seems to create another shadow root under different ID (i.e. `host-copy-network-modal`). Sometimes the IDs used are very different, sometimes they seem a typo (like the example with `HostCopyNetworksModal` and there are cases where the ID is the same i.e. `VmExportModal`. Do we need 2 shadow roots here? If not then perhaps the `PluginApiModel` can wait until `modalContext.renderContainer` will show up.

There are not 2 shadow roots.  The `PluginApiModal` works through the `useWebadminContext()` hook.  The hook will use a render container (contained within a shadow dom) if one is available via context, or will directly create/destroy one if no context is available.  So the context is setup in `renderComponent()` for the modal integrations (a 1 for 1 mapping), but is NOT setup for the place integrations / dashboard (a 1 to many mapping).

**Comment by rszwajko** [comment]
> So the context is setup in `renderComponent()` for the modal integrations (a 1 for 1 mapping), but is NOT setup for the place integrations / dashboard (a 1 to many mapping).
>

Thanks for clarifying! If both paths are mutually exclusive **and** if `id` and `modalContext` references stay stable then we could encapsulate the shadow root logic inside the hook i.e. sth similar to this (untested) snippet
```
export function useWebAdminContext (id) {
  const modalContext = useContext(WebAdminModalContext)
  const shadowRoot = useRef(null)

  useEffect(() => {
    if (modalContext) {
      return
    }

    shadowRoot.current = buildAndAppendShadowroot({ renderContainerId: id })

    return () => {
      if (shadowRoot.current) {
        shadowRoot.current.removeShadowRoot()
        shadowRoot.current = null
      }
    }
  }, [id, modalContext])

  return {
    renderContainer: modalContext?.renderContainer ?? shadowRoot.current?.renderContainer,
  }
}
```

**Comment by sjd78** [comment]
> @sjd78
> 
> > So the context is setup in `renderComponent()` for the modal integrations (a 1 for 1 mapping), but is NOT setup for the place integrations / dashboard (a 1 to many mapping).
> 
> Thanks for clarifying! If both paths are mutually exclusive **and** if `id` and `modalContext` references stay stable then we could encapsulate the shadow root logic inside the hook i.e. sth similar to this (untested) snippet
> 
> ```
> export function useWebAdminContext (id) {
>   const modalContext = useContext(WebAdminModalContext)
>   const shadowRoot = useRef(null)
> 
>   useEffect(() => {
>     if (modalContext) {
>       return
>     }
> 
>     shadowRoot.current = buildAndAppendShadowroot({ renderContainerId: id })
> 
>     return () => {
>       if (shadowRoot.current) {
>         shadowRoot.current.removeShadowRoot()
>         shadowRoot.current = null
>       }
>     }
>   }, [id, modalContext])
> 
>   return {
>     renderContainer: modalContext?.renderContainer ?? shadowRoot.current?.renderContainer,
>   }
> }
> ```

The `id` and `modalContext` should be stable, but this will also create a shadowRoot container any time the hook is used.  That would be ok for `renderComponent` modals.  For dashbaord modals, it leaves a bit of a weirdness.  There is no need to project the shadowRoot to the webadmin window until the modal actually needs to be displayed.  That's why the `PluginApiModal` builds and destroys following the `isOpen` flag.

So humm....probably could add `isOpen` to the hook and go from there.  I'll have a think about it.

**Comment by sjd78** [comment]
@rszwajko - I used `isOpen` on the hook so the shadow dom and containers are not created until the modal is going to be shown, at least for non `renderComponent` modals...have a look.

**Review by rszwajko — APPROVED** [review]

**Comment by sjd78** [comment]
Note: OST is failing because selenium tests, as currenlty written, cannot select elements under the modal's shadow-dom.

This screen shot shows the cluster upgrade modal and how the containing DIV has NO children.  All of the content lives under the shadow root:
Screenshot from 2022-09-22 11-20-51

OST needs to be updated to detect the shadow dom modals and use the `shadow_root` to work on elements in the modal.

**Comment by sjd78** [comment]
Note 2: See https://github.com/oVirt/ovirt-system-tests/pull/283 for changes to OST to handle shadow dom.

**Comment by ljelinkova** [comment]
Is the upgrade of react necessary for the shadow root to work? I think it is a risk to upgrade it now that the oVirt is not under active development and testing any more.

**Comment by sjd78** [comment]
> Is the upgrade of react necessary for the shadow root to work?

Yes, the newer react version is required.

> Is there any particular reason why we want to upgrade?

The way react handles events used to be one chain globally on the document. Shadow root events don't bubble up. The newer react version does event from the dom element where it was attached, so it can handle the shadow root. 

I'll dig up the articles I followed that describes things a bit better.

**Review by sgratch — APPROVED** [review]

**Pull request merged**
